[package]
name = "segs-plot"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
egui = { workspace = true, default-features = false }
egui_plot.workspace = true

[features]
default = []
serde = ["egui_plot/serde"]
