[package]
name = "segs"
version = "0.1.0"
# if you're a contributor, you should add your name here
authors = ["Federico Lolli <federico.lolli@skywarder.eu>"]
edition = "2021"
description = "Skyward Enhanced Ground Station"
license = "MIT"

[dependencies]
# ======= GUI & Rendering =======
egui_tiles = "0.10"
eframe = "0.29"
egui = { version = "0.29", features = ["log"] }
egui_plot = "0.29"
# ========= Persistency =========
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# =========== Logging ===========
env_logger = "0.11"
log = "0.4"
# =========== Utility ===========
# for dynamic dispatch
enum_dispatch = "0.3"
