[package]
name = "segs"
version = "0.1.0"
# if you're a contributor, you should add your name here
authors = ["Federico Lolli <federico.lolli@skywarder.eu>"]
edition = "2024"
description = "Skyward Enhanced Ground Software"
license = "MIT"

[dependencies]
# ======= GUI & Rendering =======
egui_tiles = "0.12"
eframe = { version = "0.31", features = ["persistence"] }
egui = { version = "0.31", features = ["log"] }
egui_extras = "0.31"
egui_plot = "0.31"
egui_file = "0.22"
# =========== Asynchronous ===========
tokio = { version = "1.41", features = ["rt-multi-thread", "net", "sync"] }
# =========== Mavlink ===========
serialport = "4.7.0"
# ========= Persistency =========
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# =========== Tracing and profiling ===========
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-tracy = "0.11.4"
profiling = { version = "1.0", features = ["profile-with-tracy"] }
tracing-appender = "0.2"
# =========== Utility ===========
# for dynamic dispatch
enum_dispatch = "0.3"
strum = "0.26"
strum_macros = "0.26"
anyhow = "1.0"
ring-channel = "0.12.0"
thiserror = "2.0.7"

[dependencies.skyward_mavlink]
git = "https://git.skywarder.eu/avn/swd/mavlink/mavlink-skyward-lib.git"
rev = "03d37888f7b5a84b5032ca1af392a16da7f39df2"
features = ["reflection", "orion", "serde"]

[dependencies.mavlink-bindgen]
git = "https://git.skywarder.eu/avn/swd/mavlink/rust-mavlink.git"
rev = "da4add3de8243d3b8194b9793677e4c950686ddc"
features = ["serde"]

[dev-dependencies]
rand = "0.9.0"
