[package]
name = "segs"
version = "0.1.0"
# if you're a contributor, you should add your name here
authors = ["Federico Lolli <federico.lolli@skywarder.eu>"]
edition = "2021"
description = "Skyward Enhanced Ground Software"
license = "MIT"

[dependencies]
# ======= GUI & Rendering =======
egui_tiles = "0.10"
eframe = { version = "0.29", features = ["persistence"] }
egui = { version = "0.29", features = ["log"] }
egui_plot = "0.29"
egui_file = "0.19"
# =========== Asynchronous ===========
tokio = { version = "1.41", features = ["rt-multi-thread"] }
# ========= Persistency =========
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# =========== Logging ===========
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# =========== Utility ===========
# for dynamic dispatch
enum_dispatch = "0.3"
egui_extras = "0.29.1"
