[package]
name = "segs"
authors.workspace = true
description.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
aho-corasick = "1.1.4"
chrono = { version = "0.4.42", features = ["serde"] }
directories = "6.0.0"
eframe.workspace = true
egui = { workspace = true, features = ["serde"] }
enum_dispatch = "0.3.13"
mimalloc = { version = "0.1.48", features = ["v3"] }
open = "5.4.0"
rand = "0.8.5"
segs-assets.path = "../segs-assets"
segs-memory.path = "../segs-memory"
segs-plot.path = "../segs-plot"
segs-ui.path = "../segs-ui"
segs-mavlink.path = "../segs-mavlink"
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0.145"
smallvec = "1.15.1"
tempfile = "3.24.0"
thiserror.workspace = true
argh = "0.1.19"
bitflags = "2.12.1"
